.\"                              hey, Emacs:   -*- nroff -*-
.\" barriers is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH BARRIERS 1 "August 23, 2003"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
barriers \- Compute local minima and energy barriers of a landscape
.SH SYNOPSIS
.B barriers
.RI [ options ]
.SH DESCRIPTION
\fBbarriers\fP reads an energy sorted list of conformations of a landscape,
and computes local minima and energy barriers of the landscape. For RNA
secondary structures, suitable input is produced by \fBRNAsubopt\fP. For each
local minimum found it prints to stdout, the conformation of the minimum,
its energy, the number of the "parent"-minimum it merges with, and the
height of the energy barrier. Additional information on each minimum, such
as saddle point conformation and basin sizes can be included via options.
A PostScript drawing of the resulting tree is written to "tree.ps" in the
current directory.
.SH OPTIONS
\fBbarriers\fP accepts the following options:
.TP
.BR  -q , " --quiet" , " --silent"
be quiet, don't do PostScript output.
.TP
.B  -v, --verbose
Print more information.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-V, \-\-version
Show version of program.
.TP
.B \-\-bsize
Print the size of of each basin in output.
.TP
.B \-\-max num
compute only the lowest \fInum\fP local minima.
.TP
.B \-\-minh delta
print only minima with energy barrier greater than \fIdelta\fP (default 0)
.TP
.B \-\-saddle
print the saddle point conformations in output
.TP
.B \-P l1=l2
Compute a minimal barrier path between local minima \fIl1\fP and
\fIl2\fP. The result will be written to the file "path.l1.l2.txt"
.TP
.B \-G graph
Set the type of configuration space, where \fIgraph\fP can be one of:
.br
.nf
RNA		RNA secondary structures (default)
RNA-noLP	canonical RNA structures (i.e. without isolated pairs)
Q2		Spin glass (strings of "+-")
Q\fIa\fP	\fIa\fP-letter hamming graph (e.g. Q3 strings of "ABC"). 
T		Phylogenetic Trees in bracket notation, e.g.
		((1)(((2)(3))(5))(4))
P		Permutations (as comma separated list), e.g.
		5,1,4,2,3
.br	
.fi
The type of landscape may also be set by the input file using the
fourth word on first line. E.g.:
.br
AUCGUGAGCUGUGUAGCUUAGCUAGCUAGC -610 100 :: RNA-noLP
.br
for an landscape of canonical RNA structures
.TP
.B \-M move-set
Set the moveset for generating neighbors of a configuration. For RNA possible
values are \fIShift\fP (default) or \fInoShift\fP. For Permutations
possibilities are, \fIT\fP for transpositions (default), \fIC\fP for canonical
transpositions, and \fIR\fP for reversal moves. Spin Glass always uses
point mutations (single spin flip), Trees use NNI (Nearest Neighbour
Interchange). 

.SH "SEE ALSO"
.BR RNAsubopt (1), 
.SH AUTHOR
Ivo Hofacker, Christoph Flamm, Peter Stadler. Send comments to
<ivo@tbi.univie.ac.at>.
