[AUTHOR]

Ivo Hofacker, Christoph Flamm, Peter Stadler, Michael T. Wolfinger

[>REFERENCES]

Ch. Flamm, I.L. Hofacker, P.F. Stadler, M.T. Wolfinger.
"Barrier trees of degenerate landscapes"
Z. Phys. Chem., 216:155\-173 (2002)

Ligand support has been added with version 1.7.0, see

M.T. Wolfinger, Ch. Flamm, I.L. Hofacker
"Efficient computation of cotranscriptional RNA-ligand interaction dynamics"
Methods, (2018)

[SEE ALSO]

RNAsubopt(1),treekin(1)
